2024-11-26 21:29:37,131 – [WARNING] | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/eshelenok/PycharmProjectsForUniversity/PythonPractice/Module_12/tests_12_4/tests_12_4.py", line 25, in test_run
    test_r = rt_with_exceptions.Runner(50)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eshelenok/PycharmProjectsForUniversity/PythonPractice/Module_12/tests_12_4/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-26 21:29:37,132 – [WARNING] | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/eshelenok/PycharmProjectsForUniversity/PythonPractice/Module_12/tests_12_4/tests_12_4.py", line 14, in test_walk
    test_r = rt_with_exceptions.Runner('tst', -10)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eshelenok/PycharmProjectsForUniversity/PythonPractice/Module_12/tests_12_4/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
